"""Render a :class:`Report` as a single self-contained HTML file.

The HTML embeds its own CSS so it can be opened or emailed without any external
assets or network access. Content mirrors the Markdown report. Rendering is
deterministic (Jinja2 with autoescaping, fixed iteration order).
"""

from __future__ import annotations

from jinja2 import Environment

from ..models import Posture, Report
from . import text

_POSTURE_LABEL = {
    Posture.BLOCKED: "Blocked",
    Posture.REVIEW: "Review",
    Posture.ALLOWED: "Allowed",
}

_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Open-source licence risk report</title>
<style>
  body { font-family: Georgia, "Times New Roman", serif; color: #1a1a1a;
         max-width: 60rem; margin: 2rem auto; padding: 0 1.25rem; line-height: 1.5; }
  h1 { font-size: 1.7rem; border-bottom: 2px solid #333; padding-bottom: .4rem; }
  h2 { font-size: 1.25rem; margin-top: 2rem; border-bottom: 1px solid #ccc; padding-bottom: .2rem; }
  h3 { font-size: 1.05rem; margin-top: 1.4rem; }
  table { border-collapse: collapse; width: 100%; margin: .8rem 0; font-size: .9rem; }
  th, td { border: 1px solid #cfcfcf; padding: .4rem .55rem; text-align: left; vertical-align: top; }
  th { background: #f2f2f2; }
  code { font-family: "SFMono-Regular", Consolas, monospace; font-size: .85em; background: #f4f4f4; padding: .05rem .3rem; }
  .disclaimer { background: #fff7e6; border: 1px solid #e0c080; padding: 1rem; margin: 1rem 0; }
  .summary { background: #f6f8fa; border: 1px solid #d0d7de; padding: 1rem 1.25rem; }
  .pill { display: inline-block; padding: .1rem .55rem; border-radius: .8rem; font-size: .8rem;
          font-weight: bold; color: #fff; }
  .blocked { background: #b3261e; } .review { background: #b26a00; } .allowed { background: #1e7d34; }
  .muted { color: #555; }
  footer { margin-top: 2.5rem; font-size: .8rem; color: #555; border-top: 1px solid #ccc; padding-top: .8rem; }
</style>
</head>
<body>
<h1>Open-source licence risk report</h1>
<p class="muted">Generated by {{ report.tool_name }} {{ report.tool_version }} on {{ report.generated_at }}.</p>
<div class="disclaimer"><strong>This report is automated and is not legal advice.</strong>
  See the full disclaimer at the end.</div>

<h2>Executive summary</h2>
<div class="summary">
  <p><strong>Overall release posture:</strong>
     <span class="pill {{ report.overall_posture.value }}">{{ posture_label[report.overall_posture] }}</span></p>
  <p>Blocked: <strong>{{ report.counts.blocked }}</strong> &nbsp;
     Review: <strong>{{ report.counts.review }}</strong> &nbsp;
     Allowed: <strong>{{ report.counts.allowed }}</strong> &nbsp;
     Total: <strong>{{ report.counts.total }}</strong></p>
  <p>{{ overall_sentence }}</p>
</div>
<p>Scenario assessed: shipping these components inside a proprietary, commercially distributed product.</p>
<p class="muted">Source SBOM: <code>{{ report.source_path }}</code> ({{ report.source_format.value }}).
   Policy: {{ report.policy_name }}{% if report.exceptions_path %}. Exceptions: <code>{{ report.exceptions_path }}</code>{% endif %}.</p>

<h2>Risk register</h2>
<table>
  <thead><tr><th>Component</th><th>Version</th><th>Licence</th><th>Category</th><th>Posture</th><th>Rule applied</th></tr></thead>
  <tbody>
  {% for r in report.results %}
    <tr>
      <td>{{ r.component.name }}</td>
      <td>{{ r.component.display_version }}</td>
      <td>{{ r.licence.expression or r.licence.raw or "—" }}</td>
      <td>{{ r.classification.category }}</td>
      <td><span class="pill {{ r.posture.value }}">{{ posture_label[r.posture] }}</span></td>
      <td><code>{{ r.classification.rule_id }}</code></td>
    </tr>
  {% endfor %}
  </tbody>
</table>

{% set blocked = report.results | selectattr("posture.value", "equalto", "blocked") | list %}
{% if blocked %}
<h3>Blocked components</h3>
<ul>{% for r in blocked %}<li><strong>{{ r.component.identifier }}</strong> — {{ r.classification.explanation }}</li>{% endfor %}</ul>
{% endif %}

<h2>Unresolved and unknown components</h2>
{% if report.unresolved %}
<p>These components had no usable licence information in the SBOM and were given the
   policy's conservative default. They must be resolved before any distribution decision.</p>
<ul>{% for r in report.unresolved %}
  <li><strong>{{ r.component.identifier }}</strong> — {{ r.licence.unresolved_reason or "No licence found." }}
      (posture: {{ posture_label[r.posture] }})</li>
{% endfor %}</ul>
{% else %}<p>None. Every component carried a recognised licence expression.</p>{% endif %}

<h2>Obligations to satisfy before distribution</h2>
{% if report.obligations %}
<p>These obligations are aggregated from the allowed and review components. They are
   not exhaustive and depend on how each component is used.</p>
<ul>{% for ob in report.obligations %}<li>{{ ob }}</li>{% endfor %}</ul>
{% else %}<p>No obligations were derived; resolve the blocked or unresolved components first.</p>{% endif %}

<h2>Exceptions applied</h2>
{% if report.exceptions_applied %}
<table>
  <thead><tr><th>Component</th><th>Version</th><th>From</th><th>To</th><th>Owner</th><th>Date</th><th>Justification</th></tr></thead>
  <tbody>
  {% for e in report.exceptions_applied %}
    <tr><td>{{ e.component }}</td><td>{{ e.version or "any" }}</td>
        <td>{{ e.original_posture.value }}</td><td>{{ e.override_posture.value }}</td>
        <td>{{ e.owner }}</td><td>{{ e.date }}</td><td>{{ e.justification }}</td></tr>
  {% endfor %}
  </tbody>
</table>
{% else %}<p>None.</p>{% endif %}

{% set vuln_rows = report.results | selectattr("component.vulnerabilities") | list %}
{% if vuln_rows %}
<h2>Vulnerability data carried in the SBOM (informational)</h2>
<p>This data was already present in the SBOM. This tool does not generate or verify it
   and is not a vulnerability scanner.</p>
<ul>{% for r in vuln_rows %}<li>{{ r.component.identifier }}: {{ r.component.vulnerabilities | sort | join(", ") }}</li>{% endfor %}</ul>
{% endif %}

<h2>Methodology</h2>
<ul>{% for item in methodology %}<li>{{ item }}</li>{% endfor %}</ul>

<h2>Limitations</h2>
<ul>{% for item in limitations %}<li>{{ item }}</li>{% endfor %}</ul>

<h2>Disclaimer</h2>
<div class="disclaimer">{{ disclaimer }}</div>

<footer>Generated by {{ report.tool_name }} {{ report.tool_version }}. Policy: {{ report.policy_name }}.</footer>
</body>
</html>
"""


def render(report: Report) -> str:
    env = Environment(autoescape=True, trim_blocks=True, lstrip_blocks=True)
    template = env.from_string(_TEMPLATE)
    html = template.render(
        report=report,
        posture_label=_POSTURE_LABEL,
        overall_sentence=_overall_sentence(report),
        methodology=text.METHODOLOGY,
        limitations=text.LIMITATIONS,
        disclaimer=text.DISCLAIMER,
    )
    return html if html.endswith("\n") else html + "\n"


def _overall_sentence(report: Report) -> str:
    c = report.counts
    posture = report.overall_posture
    if posture is Posture.BLOCKED:
        lead = (
            "The component set cannot be shipped under the current policy without "
            "resolving the blocked components below or recording exceptions for them."
        )
    elif posture is Posture.REVIEW:
        lead = (
            "The component set has no blocking licences under the current policy, but "
            "one or more components require legal review before distribution."
        )
    else:
        lead = (
            "Every component is classified as allowed under the current policy. The "
            "attribution obligations below must still be satisfied before distribution."
        )
    return (
        f"{lead} Of {c.total} components, {c.blocked} are blocked, {c.review} require "
        f"review, and {c.allowed} are allowed."
    )
