"""Render a :class:`Report` as Markdown written for a legal reader."""

from __future__ import annotations

from ..models import Posture, Report
from . import text

_POSTURE_LABEL = {
    Posture.BLOCKED: "Blocked",
    Posture.REVIEW: "Review",
    Posture.ALLOWED: "Allowed",
}


def _esc(value: str | None) -> str:
    if value is None:
        return ""
    return value.replace("|", "\\|").replace("\n", " ").strip()


def _overall_sentence(report: Report) -> str:
    c = report.counts
    posture = report.overall_posture
    if posture is Posture.BLOCKED:
        lead = (
            "The component set cannot be shipped under the current policy without "
            "resolving the blocked components below or recording exceptions for them."
        )
    elif posture is Posture.REVIEW:
        lead = (
            "The component set has no blocking licences under the current policy, but "
            "one or more components require legal review before distribution."
        )
    else:
        lead = (
            "Every component is classified as allowed under the current policy. The "
            "attribution obligations below must still be satisfied before distribution."
        )
    return (
        f"{lead} Of {c.total} components, {c.blocked} are blocked, {c.review} require "
        f"review, and {c.allowed} are allowed."
    )


def render(report: Report) -> str:
    lines: list[str] = []
    a = lines.append

    a("# Open-source licence risk report")
    a("")
    a(f"Generated by {report.tool_name} {report.tool_version} on {report.generated_at}.")
    a("")
    a("> This report is automated and is not legal advice. See the disclaimer at the end.")
    a("")

    # Executive summary
    a("## Executive summary")
    a("")
    a(f"- **Overall release posture: {_POSTURE_LABEL[report.overall_posture]}**")
    a(f"- Blocked: {report.counts.blocked}")
    a(f"- Review: {report.counts.review}")
    a(f"- Allowed: {report.counts.allowed}")
    a(f"- Total components assessed: {report.counts.total}")
    a("")
    a(_overall_sentence(report))
    a("")
    a(
        "Scenario assessed: shipping these components inside a proprietary, "
        "commercially distributed product."
    )
    a("")
    a(
        f"Source SBOM: `{report.source_path}` ({report.source_format.value}). "
        f"Policy: {report.policy_name}"
        + (f". Exceptions: `{report.exceptions_path}`." if report.exceptions_path else ".")
    )
    a("")

    # Risk register
    a("## Risk register")
    a("")
    a("| Component | Version | Licence | Category | Posture | Rule applied |")
    a("| --- | --- | --- | --- | --- | --- |")
    for r in report.results:
        lic = r.licence.expression or (r.licence.raw or "—")
        a(
            f"| {_esc(r.component.name)} | {_esc(r.component.display_version)} | "
            f"{_esc(lic)} | {r.classification.category} | "
            f"{_POSTURE_LABEL[r.posture]} | `{_esc(r.classification.rule_id)}` |"
        )
    a("")

    # Blocked detail
    blocked = [r for r in report.results if r.posture is Posture.BLOCKED]
    if blocked:
        a("### Blocked components")
        a("")
        for r in blocked:
            a(f"- **{_esc(r.component.identifier)}** — {_esc(r.classification.explanation)}")
        a("")

    # Unresolved / unknown
    a("## Unresolved and unknown components")
    a("")
    if report.unresolved:
        a(
            "These components had no usable licence information in the SBOM and were "
            "given the policy's conservative default. They must be resolved before "
            "any distribution decision."
        )
        a("")
        for r in report.unresolved:
            reason = r.licence.unresolved_reason or "No licence found."
            a(
                f"- **{_esc(r.component.identifier)}** — {_esc(reason)} "
                f"(posture: {_POSTURE_LABEL[r.posture]})"
            )
        a("")
    else:
        a("None. Every component carried a recognised licence expression.")
        a("")

    # Obligations
    a("## Obligations to satisfy before distribution")
    a("")
    if report.obligations:
        a(
            "These obligations are aggregated from the allowed and review components. "
            "They are not exhaustive and depend on how each component is used."
        )
        a("")
        for ob in report.obligations:
            a(f"- {ob}")
        a("")
    else:
        a(
            "No obligations were derived. This usually means every component is blocked "
            "or unresolved; resolve those first."
        )
        a("")

    # Exceptions applied
    a("## Exceptions applied")
    a("")
    if report.exceptions_applied:
        a("| Component | Version | From | To | Owner | Date | Justification |")
        a("| --- | --- | --- | --- | --- | --- | --- |")
        for e in report.exceptions_applied:
            a(
                f"| {_esc(e.component)} | {_esc(e.version or 'any')} | "
                f"{e.original_posture.value} | {e.override_posture.value} | "
                f"{_esc(e.owner)} | {_esc(e.date)} | {_esc(e.justification)} |"
            )
        a("")
    else:
        a("None.")
        a("")

    # Optional vulnerability section
    vuln_rows = [r for r in report.results if r.component.vulnerabilities]
    if vuln_rows:
        a("## Vulnerability data carried in the SBOM (informational)")
        a("")
        a(
            "This data was already present in the SBOM. This tool does not generate or "
            "verify it and is not a vulnerability scanner."
        )
        a("")
        for r in vuln_rows:
            ids = ", ".join(sorted(r.component.vulnerabilities))
            a(f"- {_esc(r.component.identifier)}: {_esc(ids)}")
        a("")

    # Methodology
    a("## Methodology")
    a("")
    for item in text.METHODOLOGY:
        a(f"- {item}")
    a("")

    # Limitations
    a("## Limitations")
    a("")
    for item in text.LIMITATIONS:
        a(f"- {item}")
    a("")

    # Disclaimer
    a("## Disclaimer")
    a("")
    a(text.DISCLAIMER)
    a("")

    return "\n".join(lines)
