"""Assemble the third-party attribution notices file (the cargo-about equivalent).

For each distributed component this collects the attribution a downstream
recipient must be given: the component name and version, its supplier and
copyright line where known, its licence, and any licence/notice text that was
actually carried in the SBOM. Licence text is never fabricated. Where the SBOM
did not carry the text, the entry says so and points to the SPDX identifier.

Blocked and unresolved components are listed in a separate, clearly labelled
section: their attribution requirements cannot be settled until the licence
question is resolved, so they must not be presented as cleared for distribution.
"""

from __future__ import annotations

from ..models import ComponentResult, Posture, Report

_HEADER = (
    "THIRD-PARTY SOFTWARE NOTICES AND ATTRIBUTIONS\n"
    "Generated by {tool} {version} on {date}.\n\n"
    "This file lists third-party components and the attribution required for "
    "their distribution. Licence texts reproduced below were taken from the "
    "supplied SBOM; where a component's text was not in the SBOM, that is stated "
    "and the SPDX licence identifier is given instead. This file is automated and "
    "is not legal advice; confirm completeness before distribution.\n"
)


def _entry_lines(r: ComponentResult) -> list[str]:
    c = r.component
    lines = [f"{c.name} {c.display_version}"]
    if c.supplier:
        lines.append(f"  Supplier: {c.supplier}")
    if c.copyright:
        lines.append(f"  {c.copyright}")
    licence = r.licence.expression or r.licence.raw or "Unknown"
    lines.append(f"  Licence: {licence}")
    if c.license_texts:
        for label, txt in sorted(c.license_texts.items()):
            lines.append(f"  --- Licence text ({label}) ---")
            for line in txt.strip().splitlines():
                lines.append(f"  {line.rstrip()}")
    elif r.licence.license_ids:
        ids = ", ".join(r.licence.license_ids)
        lines.append(
            f"  Full licence text not included in the SBOM; refer to the SPDX "
            f"licence text for: {ids}."
        )
    return lines


def render_text(report: Report) -> str:
    out: list[str] = [
        _HEADER.format(tool=report.tool_name, version=report.tool_version, date=report.generated_at)
    ]
    shippable = [
        r
        for r in report.results
        if r.posture is not Posture.BLOCKED and not r.classification.unresolved
    ]
    deferred = [
        r for r in report.results if r.posture is Posture.BLOCKED or r.classification.unresolved
    ]

    out.append("=" * 70)
    out.append("COMPONENTS")
    out.append("=" * 70)
    out.append("")
    if shippable:
        for r in shippable:
            out.extend(_entry_lines(r))
            out.append("")
    else:
        out.append("(No components were classified as distributable; see the deferred section.)")
        out.append("")

    if deferred:
        out.append("=" * 70)
        out.append("DEFERRED — NOT CLEARED FOR DISTRIBUTION")
        out.append("=" * 70)
        out.append(
            "The following components are blocked or have unresolved licences. Their "
            "attribution requirements cannot be finalised until that is resolved.\n"
        )
        for r in deferred:
            reason = (
                r.licence.unresolved_reason
                if r.classification.unresolved
                else f"posture: {r.posture.value}"
            )
            out.append(
                f"{r.component.name} {r.component.display_version} "
                f"({r.licence.expression or r.licence.raw or 'no licence'}) — {reason}"
            )
        out.append("")

    return "\n".join(out).rstrip() + "\n"


def render_markdown(report: Report) -> str:
    out: list[str] = []
    a = out.append
    a("# Third-party software notices and attributions")
    a("")
    a(f"Generated by {report.tool_name} {report.tool_version} on {report.generated_at}.")
    a("")
    a(
        "This file lists third-party components and the attribution required for their "
        "distribution. Licence texts reproduced below were taken from the supplied SBOM; "
        "where a component's text was not in the SBOM, that is stated and the SPDX "
        "identifier is given instead. This file is automated and is not legal advice."
    )
    a("")

    shippable = [
        r
        for r in report.results
        if r.posture is not Posture.BLOCKED and not r.classification.unresolved
    ]
    deferred = [
        r for r in report.results if r.posture is Posture.BLOCKED or r.classification.unresolved
    ]

    a("## Components")
    a("")
    if not shippable:
        a("_No components were classified as distributable; see the deferred section._")
        a("")
    for r in shippable:
        c = r.component
        a(f"### {c.name} {c.display_version}")
        a("")
        if c.supplier:
            a(f"- Supplier: {c.supplier}")
        if c.copyright:
            a(f"- {c.copyright}")
        a(f"- Licence: {r.licence.expression or r.licence.raw or 'Unknown'}")
        a("")
        if c.license_texts:
            for label, txt in sorted(c.license_texts.items()):
                a(f"<details><summary>Licence text ({label})</summary>")
                a("")
                a("```")
                a(txt.strip())
                a("```")
                a("</details>")
                a("")
        elif r.licence.license_ids:
            ids = ", ".join(r.licence.license_ids)
            a(
                f"Full licence text not included in the SBOM; refer to the SPDX licence "
                f"text for: {ids}."
            )
            a("")

    if deferred:
        a("## Deferred — not cleared for distribution")
        a("")
        a(
            "These components are blocked or have unresolved licences. Their attribution "
            "requirements cannot be finalised until that is resolved."
        )
        a("")
        for r in deferred:
            reason = (
                r.licence.unresolved_reason
                if r.classification.unresolved
                else f"posture: {r.posture.value}"
            )
            a(
                f"- {r.component.name} {r.component.display_version} "
                f"({r.licence.expression or r.licence.raw or 'no licence'}) — {reason}"
            )
        a("")

    return "\n".join(out)
