"""Shared prose for reports: the disclaimer, methodology and limitations.

Kept in one place so the Markdown, HTML and JSON outputs carry identical wording.
This text is a hard requirement of the tool: every report must state plainly that
the classification is automated and is not legal advice.
"""

from __future__ import annotations

DISCLAIMER = (
    "This report is generated by automated tooling. It is not legal advice and "
    "does not create a lawyer-client relationship. The classifications are "
    "indicative only: they are produced by applying a configurable policy to the "
    "licence identifiers found in the supplied SBOM. They depend entirely on the "
    "policy in force and on the completeness and accuracy of that SBOM. They do "
    "not account for how each component is actually used, combined, linked or "
    "distributed in your product, and they do not constitute a determination that "
    "any component may or may not be shipped. Before making any distribution "
    "decision, the findings here must be reviewed by qualified legal counsel."
)

METHODOLOGY = [
    "Each component's licence is read from the SBOM. The concluded licence is "
    "preferred over the declared licence where both are present.",
    "Licence strings are parsed as SPDX expressions, including AND, OR and WITH "
    "operators, using the SPDX licence list.",
    "Each licence is mapped to a category and a ship-posture by the policy file. "
    "For a dual (OR) licence the least restrictive branch governs by default, "
    "because the distributor may elect it; for an AND every licence applies and "
    "the most restrictive governs.",
    "Licences that are NOASSERTION, absent, or not recognised are never treated "
    "as acceptable by default. They are surfaced as unresolved or unknown and "
    "given the policy's conservative default posture.",
    "Project exceptions, where supplied, are applied after classification and are "
    "listed with their justification, owner and date.",
    "Every result records the policy rule that produced it, so each classification "
    "can be audited.",
]

LIMITATIONS = [
    "This tool does not perform static or dynamic linkage analysis. Weak-copyleft "
    "obligations (for example LGPL or MPL) depend on how a component is linked, "
    "which must be assessed by a human.",
    "It classifies licences; it does not read the full licence text or detect "
    "additional terms embedded in a component.",
    "It is not a vulnerability scanner. Where the SBOM already contains "
    "vulnerability data it is surfaced for information only.",
    "It does not assert compliance with the EU Cyber Resilience Act or any other "
    "regulation, and is not a certification. It is a readiness and analysis aid.",
    "Its conclusions are only as good as the SBOM it is given. Components missing "
    "from the SBOM are invisible to it.",
]

POSTURE_MEANING = {
    "allowed": "Acceptable under the policy for a proprietary, distributed product.",
    "review": "A human must read the terms and the usage before shipping.",
    "blocked": "Not acceptable under the policy without a recorded exception.",
}
